name: SSH into Oracle Linux

on:
  push:
    branches:
      -  "Sprint-3" 

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: SSH into Oracle Linux
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHOCI }}
          script: |
            sudo su
            
            cd /home/opc/GJ+/GJ-Platform
            git pull origin Sprint-3

            sudo chown -R ${{ secrets.USERNAME }}:$USER /home/opc/GJ+/GJ-Platform/Frontend/GJ-Platform/node_modules


            cd /home/opc/GJ+/GJ-Platform/Frontend/GJ-Platform
            ng build --configuration production
            
            cd /home/opc/GJ+/GJ-Platform/back-end

            sudo npm install pm2 -g
            pm2 start index.js --name "sprint-3"
            pm2 restart sprint-3

