name: SSH into Oracle Linux

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Oracle Linux
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHOCI }}
          script: |
            cd /home/opc/Documents/main/GJ-Platform
            git pull origin main
            cd /home/opc/Documents/main/GJ-Platform/Frontend/GJ-Platform
            ng build --configuration production
            # Ejecuta otros comandos según sea necesario
            cd /home/opc/Documents/main/GJ-Platform/back-end
            node index.js