name: SSH into Oracle Linux

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: SSH into Oracle Linux
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHOCI }}
          script: |
            cd /home/opc/Documents/main/GJ-Platform
            git config --global --add safe.directory /home/opc/Documents/main/GJ-Platform
            git pull origin main
            cd /home/opc/Documents/main/GJ-Platform/Frontend/GJ-Platform
            npm install -g @angular/cli 
            ng build --configuration production
            # Ejecuta otros comandos según sea necesario
            cd /home/opc/Documents/main/GJ-Platform/back-end
            npm i
            node index.js
            # Ejecuta otros comandos según sea necesario
