# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: Red Hat Enterprise Linux release 8.9

    strategy:
      matrix:
        node-version: [20.11.1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Change directory to backend
      run: cd GJ-Platform/backend
      
    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
